In [1]:
import numpy as np

## Input e Output de arrays em arquivos
Com o NumPy é possível gravar/ler arrays em arquivos, seja em formato binário ou em texto.

### Armazenando arrays em disco com formato binário
`np.save` e `np.load` são as duas funções utilizadas para salvar e ler arrays de um arquivo em disco. Arrays são salvos em formato binário por padrão e utilizando a extensão **.npy**.

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.save('some_array', arr)
# Gera um arquivo some_array.npy no diretório do notebook

In [4]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Podemos gravar multiplos arrays utilizando a função **savez** e passando como os arrays como palavras chaves:

In [5]:
np.savez('array_mult.npz', a=arr, b=arr)

Ao ler um arquivo com a extensão **.npz** o resultado é um objeto semelhante ao dicionário onde os arrays podem ser encontrado nas chaves que lhes foram atribuidas pela função **savez**.

In [6]:
arr = np.load('array_mult.npz')
arr

In [7]:
arr['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Armazenando arrays em formato de texto


## Álgebra Linear
Álgebra linear, multiplicação de matrizes, decomposição, determinante, e outras operações utilizadas em matrizes são uma parte importante de uma biblioteca de manipulação de arrays. Para realizarmos a multiplicação de duas matrizes podemos utilizar a função **dot** ou **np.dot**.

In [8]:
arr_one = np.array([2, 3])
arr_one

array([2, 3])

In [10]:
arr_two = np.array([[3], [3]])
arr_two

array([[3],
       [3]])

In [11]:
arr_one.dot(arr_two)

array([15])

In [12]:
np.dot(arr_one, arr_two)

array([15])

**numpy.linalg** possui um conjunto de decomposições de matrizes e outras funções como inversas e soluções de sistemas lineares e determinantes.

<table width="100%">
    <thead>
        <tr>
            <th>Função</th>
            <th colspan=3>Descrição</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><b>diag</b></td>
            <td colspan=3>Retorna os elementos da diagonal de uma matriz quadrática como um aray de uma dimensão.</td>
        </tr>
        <tr>
            <td><b>dot</b></td>
            <td colspan=3>Multiplicação de matrizes.</td>
        </tr>
        <tr>
            <td><b>trace</b></td>
            <td colspan=3>Computa a soma dos elementos da diagonal da matriz.</td>
        </tr>
        <tr>
            <td><b>det</b></td>
            <td colspan=3>Computa a determinante da matriz.</td>
        </tr>
        <tr>
            <td><b>eig</b></td>
            <td colspan=3>Computa os autovalores e autovetores de uma matriz quadrática.</td>
        </tr>
        <tr>
            <td><b>inv</b></td>
            <td colspan=3>Computa a inversa de uma matriz quadrática.</td>
        </tr>
        <tr>
            <td><b>qr</b></td>
            <td colspan=3>Computa a decomposição QR.</td>
        </tr>
        <tr>
            <td><b>svd</b></td>
            <td colspan=3>Computa a SVD de uma matriz.</td>
        </tr>
        <tr>
            <td><b>solve</b></td>
            <td colspan=3>Resolve um sistema linear Ax = b.</td>
        </tr>
    </tbody>
</table>