In [2]:
import numpy as np

# Funções universais: manipulação dos elementos de forma rápida
Uma função universal é uma função que manipula todos os elementos contidos em um array.

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [5]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

Existem funções que recebem escalares como parâmetro e outras recebem dois arrays e retornam um com os máximos de cada posição.

In [6]:
x = np.random.randn(8)
x

array([ 0.90958867,  1.69429207,  0.61494164, -1.21886048, -0.30383955,
       -0.49571623, -0.40673034, -2.01103593])

In [7]:
y = np.random.randn(8)
y

array([ 0.41121616,  0.46048895, -0.26247766, -0.97871189, -0.52744911,
        0.54537372,  0.57738752,  0.49073544])

In [8]:
np.maximum(x, y)

array([ 0.90958867,  1.69429207,  0.61494164, -0.97871189, -0.30383955,
        0.54537372,  0.57738752,  0.49073544])

## Processamento de dados usando arrays
Os arrays do NumPy permitem que manipulemos os dados contidos neles sem a necessidade de escrever **loops**, essa prática é conhecida também como vetorização. 

### Expressando lógicas condicionais como operações entre arrays
A função **numpy.where** é a função vetorizada da expressão ternária `x if condition else y`. Supondo que temos dois arrays de valores e um de condições:

In [9]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
xarr

array([1.1, 1.2, 1.3, 1.4, 1.5])

In [10]:
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
yarr

array([2.1, 2.2, 2.3, 2.4, 2.5])

In [11]:
cond = np.array([True, False, True, True, False])
cond

array([ True, False,  True,  True, False])

In [12]:
resultado = [(x if c else y)
             for x, y, c in zip(xarr, yarr, cond)]
resultado

[1.1, 2.2, 1.3, 1.4, 2.5]

Isso possui muitos problemas. Primeiro que não será muito performático para arrays com muitos elementos, principalmente pois grande parte do trabalho está sendo feito em Python puro. Segundo, não irá funcionar com arrays multidimensionais. Com o `np.where` podemos escrever isto de forma muito mais rápida e prática.

In [13]:
resultado2 = np.where(cond, xarr, yarr)
resultado2

array([1.1, 2.2, 1.3, 1.4, 2.5])

### Funções matemáticas e estatísticas
Um conjunto de funções matemáticas computa estatísticas sobre um conjunto de elementos contidos no array. Agregações, também chamadas de reduções, como `sum`(somatório), `mean`(média), e o desvio padrão (`std`), podem ser calculados através de funções de um array. 

In [14]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
arr.mean()

9.5

In [17]:
np.mean(arr)

9.5

In [16]:
arr.sum()

190

<table width='100%'>
    <thead>
        <tr>
            <th>Método</th>
            <th colspan=3>Descrição</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><b>sum</b></td>
            <td colspan=3>Realiza a soma de todos os elementos do array ou ao longo do eixo.</td>
        </tr>
        <tr>
            <td><b>mean</b></td>
            <td colspan=3>Média aritmética. Arrays com tamanho 0 possui uma média de NaN.</td>
        </tr>
        <tr>
            <td><b>std, var</b></td>
            <td colspan=3>Desvio padrão e variância, respectivamente, com ajuste opcional dos graus de liberdade (denominador padrão n).</td>
        </tr>
        <tr>
            <td><b>min, max</b></td>
            <td colspan=3>Calcula o mínimo e o máximo entre os elementos do array.</td>
        </tr>
        <tr>
            <td><b>argmin, argmax</b></td>
            <td colspan=3>Indices dos mínimos e máximos do array.</td>
        </tr>
        <tr>
            <td><b>cumsum</b></td>
            <td colspan=3>Soma acumulativa dos elementos do array começando por 0.</td>
        </tr>
        <tr>
            <td><b>cumprod</b></td>
            <td colspan=3>Produto cumulativo dos elementos do array começando por 1.</td>
        </tr>
    </tbody>
</table>

### Métodos para arrays booleanos
Os valores booleanos são padronizados como 1(True) e 0(False) nos seguintes métodos. Por exemplo, **sum**
oferece uma contagem dos valores True em um array.

In [18]:
arr = np.random.randn(100)
arr

array([-0.52180431, -0.22069117, -0.46634079,  1.34602338,  0.89877203,
        1.41039823,  0.15469391,  0.26786437, -0.61262782, -0.46903685,
       -0.29504206,  1.17536836, -0.7213881 , -1.61249504,  1.75182867,
        1.52050587, -0.89220964, -0.434337  ,  1.80661652, -1.93215275,
        0.23560365, -0.3175366 ,  0.78242697, -0.81419903,  1.41534319,
       -1.25634951, -0.86083832, -1.69573853, -1.35994801,  0.88506952,
       -0.92085655,  0.31289466,  1.61698266, -0.22876438,  0.4570779 ,
        0.28759502,  0.83927596,  0.34907497,  1.70458847,  0.48686425,
       -0.90779132,  0.9858686 ,  0.46726735, -1.10440852, -0.98708665,
       -1.46058589, -1.23134851,  0.93003045,  2.35556265, -1.48082418,
        0.09073433,  1.00386686, -0.89743459, -0.53056863, -0.82756999,
       -0.07883946, -1.59304301, -0.45616986, -1.17258586, -0.532522  ,
        0.54740264, -0.0884413 , -1.52652158, -0.50217706,  1.11098779,
        0.81885116, -1.28127434, -0.60517093, -0.13539696, -0.28

In [20]:
(arr > 0).sum()

45

Os métodos **any** e **all**, checam se no array há ao menos um valor True ou se todos os valores são True, respectivamente, e por fim retornam se a condição foi aceita.

In [22]:
bools = np.array([True, False, True, True, False, True])
bools

array([ True, False,  True,  True, False,  True])

In [23]:
bools.any()

True

In [24]:
bools.all()

False

## Ordenação
Como nas listas do Python, os arrays do NumPy podem ser ordenados utilizando o método `sort`.

In [25]:
arr = np.array([2, 1, 6, 3, 4, 5])
arr

array([2, 1, 6, 3, 4, 5])

In [27]:
arr.sort()
arr

array([1, 2, 3, 4, 5, 6])

Podemos determinar a forma como a ordenação será executada em arrays multidimensionais passando o número do eixo a qual a ordenação será aplicada.

In [28]:
arr = np.array([[6, 2, 3],[1, 5, 9]])
arr

array([[6, 2, 3],
       [1, 5, 9]])

In [29]:
arr.sort(1)
arr

array([[2, 3, 6],
       [1, 5, 9]])

## Unique e outras lógicas de conjuntos
O NumPy tem muitas funções para tratamento de conjuntos (set), a mais comumente utilizada é a função `np.unique`, que retorna um array ordenado de valores unicos.

In [30]:
nomes = np.array(['Bob', 'Mei', 'Bob', 'Mimi', 'Mimi', 'Bob'])
nomes

array(['Bob', 'Mei', 'Bob', 'Mimi', 'Mimi', 'Bob'], dtype='<U4')

In [31]:
np.unique(nomes)

array(['Bob', 'Mei', 'Mimi'], dtype='<U4')

Outra função, `np.in1d`, testa se os elementos de um array estão contidos no outro,
retornando assim um array de valores booleanos:

In [32]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.in1d(arr, [2, 3, 6])

array([False,  True,  True, False, False,  True, False, False, False])

<table width='100%'>
    <thead>
        <tr>
            <th>Método</th>
            <th colspan=3>Descrição</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><b>unique(x)</b></td>
            <td colspan=3>Computa a ordenação de elementos únicos em x.</td>
        </tr>
        <tr>
            <td><b>intersect1d(x, y)</b></td>
            <td colspan=3>Computa a ordenação dos elementos comuns em x, y.</td>
        </tr>
        <tr>
            <td><b>union1d(x, y)</b></td>
            <td colspan=3>Computa a ordenação da união do elementos.</td>
        </tr>
        <tr>
            <td><b>in1d(x, y)</b></td>
            <td colspan=3>Conjunto booleano indicando os elementos que estão em x e não estão em y.</td>
        </tr>
        <tr>
            <td><b>setdiff1d(x, y</b></td>
            <td colspan=3>.</td>
        </tr>
        <tr>
            <td><b>cumsum</b></td>
            <td colspan=3>Soma acumulativa dos elementos do array começando por 0.</td>
        </tr>
        <tr>
            <td><b>cumprod</b></td>
            <td colspan=3>Produto cumulativo dos elementos do array começando por 1.</td>
        </tr>
    </tbody>
</table>